name: Guilds
version: '${project.version}'
main: net.devscape.project.guilds.Guilds
api-version: 1.13
authors: [Reeignn]
depend:
  - Vault
softdepend:
  - PlaceholderAPI
  - StrikePractice
description: Amazing guild rich-feature plugin.
commands:
  guilds:
    description: Command for guilds.
    usage: ""
    aliases:
      - guild
      - guilds
      - g